openapi: 3.0.1
info:
  contact:
    email: dev@nextlinux.com
  description: Enterprise API for managing roles, permissions, and user mappings
  title: Nextlinux Enterprise RBAC API
  version: 0.1.0
servers:
- url: /
tags:
- description: User management
  name: Users
paths:
  /health:
    get:
      description: Health check, returns 200 and no body if service is running
      operationId: health_check
      responses:
        "200":
          content: {}
          description: Empty body on success
      x-swagger-router-controller: nextlinux_enterprise.common.common
      x-nextlinux-authz-action: None
  /version:
    get:
      description: Returns the version object for the service, including db schema
        version info
      operationId: version_check
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceVersion'
          description: Version object describing version state
      x-swagger-router-controller: nextlinux_enterprise.common.apis
      x-nextlinux-authz-action: None
  /status:
    get:
      description: Get the API service status
      operationId: get_status
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Status listing
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: Service status
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.status
      x-nextlinux-authz-action: None
  /roles:
    get:
      operationId: list_roles
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleSummaryList'
          description: Role summary listing
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: List roles available in the system
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: listRoles
  /roles/{rolename}:
    get:
      operationId: get_role
      parameters:
      - in: path
        name: rolename
        required: true
        schema:
          format: path
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
          description: Role details
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: Get detailed information about a specific role
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: getRole
  /roles/{rolename}/members:
    delete:
      operationId: delete_role_user
      parameters:
      - in: path
        name: rolename
        required: true
        schema:
          format: path
          type: string
      - description: The username to remove the role for
        in: query
        name: username
        required: true
        schema:
          type: string
      - description: The account that the user has the role to be removed
        in: query
        name: for_account
        required: true
        schema:
          type: string
      responses:
        "204":
          content: {}
          description: Success
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: Remove a user from the role
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: deleteRoleMember
    get:
      operationId: list_role_members
      parameters:
      - in: path
        name: rolename
        required: true
        schema:
          format: path
          type: string
      - description: Optional filter parameter to limit the set fo returned items
          to only those with matching account. Will return Access Denied if caller
          does not have permission to listRoleMembers for that account.
        in: query
        name: for_account
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleMemberList'
          description: List of users assigned the role
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: Returns a list of objects that have members in the role. The list is
        filtered by 'listRoleMembers' access for the 'account' element of each entry.
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: listRoleMembers
    post:
      operationId: add_role_user
      parameters:
      - in: path
        name: rolename
        required: true
        schema:
          format: path
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleMember'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleMember'
          description: Added user mapping
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: Add a user to the role
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: createRoleMember
      x-codegen-request-body-name: member
  /my_roles:
    get:
      operationId: my_roles
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRoleListing'
          description: Role summary listing
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: List the roles for which the authenticated user is a member
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: None
  /users/{username}/roles:
    get:
      operationId: list_user_roles
      parameters:
      - in: path
        name: username
        required: true
        schema:
          format: path
          type: string
      - in: query
        name: for_account
        schema:
          type: string
      - in: query
        name: role
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRoleMembership'
          description: Role summary listing
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      summary: List the roles for which the requested user is a member
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.roles
      x-nextlinux-authz-action: None
  /saml/login/{idp_name}:
    get:
      description: Initiate an SP-initiated login sequence for the Idp. The SP will
        respond with the SAML AuthN Request the client must send to the Idp URL
      operationId: saml_login
      parameters:
      - in: path
        name: idp_name
        required: true
        schema:
          format: path
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: Resulting JWT token
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
  /saml/sso/{idp_name}:
    post:
      description: Perform a login using a SAML assertion, no HTTP auth is required
        as the SAML assertion is considered the authenticating token
      operationId: saml_sso
      parameters:
      - in: path
        name: idp_name
        required: true
        schema:
          format: path
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: Resulting JWT token
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
  /saml/idps:
    get:
      description: List the names of configured Identity Providers for this nextlinux
        installation
      operationId: list_idps
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  description: Name of idp for login or config operations
                  type: string
                type: array
          description: List of idp names
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
    post:
      description: Add a new Identity Provider to the system, with a specific name
      operationId: add_idp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SamlConfiguration'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SamlConfiguration'
          description: Entry created
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Conflict, entry already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
      x-codegen-request-body-name: configuration
  /saml/idps/{name}:
    delete:
      description: Delete an idp configuration. Users will not longer be able to login
        from this idp. In addition, any users that have been configured explicitly
        or JIT Provisioned on this IDP will be deleted.
      operationId: delete_idp
      parameters:
      - in: path
        name: name
        required: true
        schema:
          format: path
          type: string
      responses:
        "204":
          content: {}
          description: Successfully deleted
        "404":
          content: {}
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
    get:
      description: Return the configuration for a named Identity Provider
      operationId: get_idp
      parameters:
      - in: path
        name: name
        required: true
        schema:
          format: path
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SamlConfiguration'
          description: Successfully retrieved configuration
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
    put:
      description: Update an existing Identity Provider configuration
      operationId: update_idp
      parameters:
      - in: path
        name: name
        required: true
        schema:
          format: path
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SamlConfiguration'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SamlConfiguration'
          description: Successfully updated configuration
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Not found
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Not found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
          description: Internal error
      x-swagger-router-controller: nextlinux_enterprise.services.rbac_manager.api.controllers.auth
      x-nextlinux-authz-action: None
      x-codegen-request-body-name: configuration
components:
  schemas:
    Role:
      description: Role definition
      example:
        immutable: true
        last_updated: 2000-01-23T04:56:07.000+00:00
        permissions:
        - action: action
          target: target
        - action: action
          target: target
        name: name
        description: description
        created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        name:
          description: The name of the role
          type: string
        description:
          description: A role description for humans
          type: string
        permissions:
          items:
            $ref: '#/components/schemas/Permission'
          type: array
        immutable:
          description: Are the permissions of this role modifiable by users (including
            admin users)
          type: boolean
        created_at:
          description: The timestamp when the role was created
          format: date-time
          type: string
        last_updated:
          description: The timestamp of the last update to the role metadata itself
          format: date-time
          type: string
      required:
      - name
      type: object
    Permission:
      description: A grant of specific action against a specific scope and target
      example:
        action: action
        target: target
      properties:
        action:
          description: The allowed action. e.g. getImage
          type: string
        target:
          description: The target to which the action may be applied. Either a '*'
            for all or a specific target id
          type: string
      type: object
    PermissionList:
      items:
        $ref: '#/components/schemas/Permission'
      type: array
    RoleMember:
      description: A mapping between a username and a role with an account context
      example:
        for_account: for_account
        created_at: 2000-01-23T04:56:07.000+00:00
        username: username
      properties:
        username:
          type: string
        for_account:
          type: string
        created_at:
          format: date-time
          type: string
      required:
      - for_account
      - username
      type: object
    RoleMemberList:
      description: List of members of the role, may be filtered by the calling user's
        access level (e.g. will not display members for which the caller doesn't have
        listRoleMembers acocunt access)
      items:
        $ref: '#/components/schemas/RoleMember'
      type: array
    RoleSummaryList:
      items:
        $ref: '#/components/schemas/RoleSummary'
      type: array
    RoleSummary:
      example:
        name: name
        description: description
        created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        name:
          type: string
        description:
          type: string
        created_at:
          format: date-time
          type: string
      type: object
    UserRoleListing:
      description: List of role mappings for a user
      items:
        $ref: '#/components/schemas/AccountRole'
      type: array
    AccountRole:
      description: An account identifier and roles a user has within that account
      example:
        for_account: for_account
        roles:
          immutable: true
          last_updated: 2000-01-23T04:56:07.000+00:00
          permissions:
          - action: action
            target: target
          - action: action
            target: target
          name: name
          description: description
          created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        for_account:
          description: The account scope that applies to the set of roles
          type: string
        roles:
          $ref: '#/components/schemas/Role'
      type: object
    UserRoleMembership:
      description: List of role mappings for a user
      items:
        $ref: '#/components/schemas/RoleMembership'
      type: array
    RoleMembership:
      description: Membership for a role in an account
      example:
        role: role
        for_account:
        - for_account
        - for_account
        created_at: 2000-01-23T04:56:07.000+00:00
      properties:
        role:
          description: The name of the role the user has permissions for
          type: string
        for_account:
          items:
            description: The accounts for which the user has the role permission
            type: string
          type: array
        created_at:
          format: date-time
          type: string
      type: object
    ApiErrorResponse:
      description: Generic HTTP API error response
      properties:
        code:
          format: int32
          type: integer
        error_type:
          type: string
        message:
          type: string
        detail:
          description: Details structure for additional information about the error
            if available. Content and structure will be error specific.
          properties: {}
          type: object
      type: object
    StatusResponse:
      description: System status response
      example:
        busy: true
        up: true
        message: message
      properties:
        busy:
          type: boolean
        up:
          type: boolean
        message:
          type: string
      type: object
    ServiceVersion:
      description: Version information for a service
      example:
        engine:
          version: version
          db: db
        service:
          version: version
        api:
          version: version
        db:
          schema_version: schema_version
      properties:
        service:
          $ref: '#/components/schemas/ServiceVersion_service'
        api:
          $ref: '#/components/schemas/ServiceVersion_api'
        db:
          $ref: '#/components/schemas/ServiceVersion_db'
        engine:
          $ref: '#/components/schemas/ServiceVersion_engine'
      type: object
    TokenResponse:
      description: An auth token for use in future requests as an Authorization header
        value of type 'bearer'
      example:
        token: token
      properties:
        token:
          description: The token content
          type: string
      required:
      - token
      type: object
    SamlConfiguration:
      description: A named configuration for interaction with an Identity Provider
        that supports SAML 2.0
      example:
        last_updated: 2000-01-23T04:56:07.000+00:00
        acs_https_port: 0
        idp_metadata_url: idp_metadata_url
        require_signed_response: true
        require_existing_users: false
        default_role: default_role
        created_at: 2000-01-23T04:56:07.000+00:00
        idp_username_attribute: idp_username_attribute
        idp_role_attribute: idp_role_attribute
        acs_url: acs_url
        sp_entity_id: sp_entity_id
        idp_account_attribute: idp_account_attribute
        enabled: true
        default_account: default_account
        name: name
        require_signed_assertions: true
        idp_metadata_xml: idp_metadata_xml
      properties:
        name:
          description: The name to use for referencing this IDP configuration. This
            will configured as part of the url string the Idp must have the client
            POST the saml assertion to.
          pattern: ^[a-zA-Z0-9_-]+$
          type: string
        enabled:
          description: If this IDP configuration should be enabled for user logins
          type: boolean
        sp_entity_id:
          description: The entity ID for this SP. Can be the same for all IDP configurations
            in this installation or unique to each. This is typically a URL, but you
            can use any value as long as you also configure the IDP to expect this
            value.
          type: string
        acs_url:
          description: The URL the IDP can use to access the Assertion Consumer Service
            to provide the token for sso. This is the way to reach the rbac manager
            services /service/sso/auth/{IDP_name} route externally
          type: string
        acs_https_port:
          description: The port number to use for https if not 443. If omitted or
            -1, 443 is assumed and used as a default
          type: integer
        idp_metadata_url:
          description: The url where the SP (nextlinux) can retrieve the metadata about
            the Identity Provider. Only one of this or metadata_xml should be set.
            This is typically provided by the IDP.
          type: string
        idp_metadata_xml:
          description: The direct metadata xml payload, if a url is not available.
            Only one of this or metadata_url should be set.
          type: string
        idp_username_attribute:
          description: The SAML attribute to use from the response assertions to determine
            the nextlinux username. If unset, the subject is used.
          type: string
        idp_account_attribute:
          description: The SAML attribute to use from the response assertions to determine
            the nextlinux account to use. If unset, the default is used.
          type: string
        idp_role_attribute:
          description: The SAML attribute to use from the response assertions to determine
            the nextlinux role(s) to assign a new user in the specified account. If
            unset, the default is used.
          type: string
        default_account:
          description: The nextlinux account to assign all users to from this IDP if
            no account attribute is mapped or present.
          type: string
        default_role:
          description: The default role to apply to new users from this IDP if no
            attribute is mapped or found in the SAML assertions.
          type: string
        require_signed_assertions:
          default: true
          description: Require assertions in to be signed from the IDP
          type: boolean
        require_signed_response:
          default: true
          description: Require the authn response to be signed by the IDP
          type: boolean
        created_at:
          format: date-time
          type: string
        last_updated:
          format: date-time
          type: string
        require_existing_users:
          default: false
          description: Indicates if Nextlinux will require an authenticating SSO user
            to already exist.  This field is ignored on POST/PUT Operations.
          type: boolean
      required:
      - acs_url
      - enabled
      - name
      - sp_entity_id
      type: object
    ServiceVersion_service:
      example:
        version: version
      properties:
        version:
          description: Semantic Version string of the service implementation
          type: string
      type: object
    ServiceVersion_api:
      description: Api Version string
      example:
        version: version
      properties:
        version:
          description: Semantic version of the api
          type: string
      type: object
    ServiceVersion_db:
      example:
        schema_version: schema_version
      properties:
        schema_version:
          description: Semantic version of the db schema
          type: string
      type: object
    ServiceVersion_engine:
      example:
        version: version
        db: db
      properties:
        version:
          description: Version of the installed engine library
          type: string
        db:
          description: Version of the installed engine db schema
          type: string
      type: object
x-original-swagger-version: "2.0"
